apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lfs-chunkserver
  namespace: lizardfs
spec:
  selector:
    matchLabels:
      app: lfs-chunkserver
  template:
    metadata:
      labels:
        app: lfs-chunkserver
    spec:
      volumes:
        - name: task-pv-storage
          hostPath:
            path: /home/lizardfs.com/k8s/lfs-chunkserver/var/lib/lizardfs/
            type: DirectoryOrCreate

        - name: task-pv-hdd
          hostPath:
            path: /home/lizardfs.com/k8s/lfs-chunkserver/hdd
            type: DirectoryOrCreate

        - name: config
          configMap:
            name: lizardfs-chunkserver-config

      containers:
      - name: chunkserver
        image: lizardfscom/chunk-server:3.12.0-focal
        ports:
        - containerPort: 9422
        volumeMounts:
         - name: task-pv-storage
           mountPath: /var/lib/lizardfs/
         - name: task-pv-hdd
           mountPath: /hdd
         - name: config
           mountPath: /etc/lizardfs/

---
apiVersion: v1
kind: Service
metadata:
  name: lfs-chunkserver
  namespace: lizardfs
  labels:
    app: lfs-chunkserver
spec:
  ports:
   - port: 9422
  selector:
    app: lfs-chunkserver
